# Generated by Django 2.0.3 on 2018-04-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_auto_20180411_1610'),
        ('plans', '0002_auto_20180411_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='MediaPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('memo', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='MediaPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, unique=True)),
                ('budget', models.BigIntegerField()),
                ('dates', models.CharField(max_length=1024)),
                ('shuffle', models.BooleanField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('approve', 'awaiting approval'), ('book', 'book publications'), ('design', 'awaiting design'), ('send', 'sending to publications'), ('complete', 'published')], default='0', max_length=15)),
                ('designer', models.CharField(max_length=1024)),
                ('starter', models.CharField(max_length=1024)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Client')),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='name',
            field=models.CharField(default='demo', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaplacement',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Design'),
        ),
        migrations.AddField(
            model_name='mediaplacement',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.File'),
        ),
        migrations.AddField(
            model_name='mediaplacement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.MediaPlan'),
        ),
        migrations.AddField(
            model_name='mediaplacement',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Rate'),
        ),
        migrations.AddField(
            model_name='design',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plans.MediaPlan'),
            preserve_default=False,
        ),
    ]
