# Generated by Django 2.0.3 on 2018-04-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_auto_20180411_1610'),
        ('plans', '0003_auto_20180411_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='audience',
            field=models.ManyToManyField(to='setup.TargetGroup'),
        ),
        migrations.AddField(
            model_name='expense',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.MediaPlan'),
        ),
    ]
