# Generated by Django 2.0.3 on 2018-04-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_auto_20180412_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='plans.MediaPlan'),
        ),
    ]
