# Generated by Django 2.0.3 on 2018-04-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_auto_20180411_1610'),
        ('plans', '0007_auto_20180412_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='plans.MediaPlan')),
                ('selectedPubs', models.ManyToManyField(to='setup.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='mediaplacement',
            name='week',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plans.Week'),
            preserve_default=False,
        ),
    ]
