# Generated by Django 2.0.3 on 2018-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20180412_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaplan',
            name='audience',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='setup.TargetGroup'),
        ),
    ]
