# Generated by Django 2.0.3 on 2018-04-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_auto_20180423_1405'),
        ('plans', '0009_auto_20180416_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMediaPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=2048)),
                ('memo', models.CharField(max_length=2048)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Design')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.File')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.MediaPlan')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Rate')),
            ],
        ),
        migrations.CreateModel(
            name='FullMediaPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('memo', models.CharField(max_length=2048)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Design')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.File')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.MediaPlan')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Rate')),
            ],
        ),
        migrations.RenameModel(
            old_name='MediaPlacement',
            new_name='WeeklyMediaPlacement',
        ),
        migrations.AlterField(
            model_name='week',
            name='selectedPubs',
            field=models.ManyToManyField(related_name='weeks', to='setup.Publication'),
        ),
        migrations.AddField(
            model_name='dailymediaplacement',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Week'),
        ),
    ]
