# Generated by Django 2.0.3 on 2018-04-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_auto_20180423_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymediaplacement',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.File'),
        ),
        migrations.AlterField(
            model_name='fullmediaplacement',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.File'),
        ),
        migrations.AlterField(
            model_name='weeklymediaplacement',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.File'),
        ),
    ]
