# Generated by Django 2.0.3 on 2018-04-23 15:05

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_auto_20180423_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deadline',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
