# Generated by Django 2.0.3 on 2018-04-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_expense_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='deadline',
        ),
    ]
