# Generated by Django 2.0.3 on 2018-04-23 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_remove_expense_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deadline',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
