# Generated by Django 2.0.3 on 2018-04-23 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_expense_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymediaplacement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ads', to='plans.MediaPlan'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='plans.MediaPlan'),
        ),
        migrations.AlterField(
            model_name='fullmediaplacement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_ads', to='plans.MediaPlan'),
        ),
        migrations.AlterField(
            model_name='weeklymediaplacement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_ads', to='plans.MediaPlan'),
        ),
    ]
