# Generated by Django 2.0.3 on 2018-04-24 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_auto_20180423_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaplan',
            name='dates',
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='endDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='startDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
