# Generated by Django 2.0.3 on 2018-04-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0017_auto_20180424_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymediaplacement',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ads', to='plans.Design'),
        ),
        migrations.AlterField(
            model_name='dailymediaplacement',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ads', to='plans.Week'),
        ),
        migrations.AlterField(
            model_name='fullmediaplacement',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_ads', to='plans.Design'),
        ),
        migrations.AlterField(
            model_name='weeklymediaplacement',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_ads', to='plans.Design'),
        ),
        migrations.AlterField(
            model_name='weeklymediaplacement',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_ads', to='plans.Week'),
        ),
    ]
