# Generated by Django 2.0.3 on 2018-04-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0018_auto_20180430_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymediaplacement',
            name='status',
            field=models.CharField(default='pending', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fullmediaplacement',
            name='status',
            field=models.CharField(default='pending', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklymediaplacement',
            name='status',
            field=models.CharField(default='pending', max_length=24),
            preserve_default=False,
        ),
    ]
