# Generated by Django 2.0.3 on 2018-03-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('contactName', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=1024)),
                ('phone', models.CharField(max_length=1024)),
                ('logo', models.ImageField(upload_to='', verbose_name='uploads/publications/')),
                ('recurrence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('full campaign', 'Full Campaign')], default='weekly', max_length=15)),
            ],
        ),
    ]
