# Generated by Django 2.0.3 on 2018-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='targetGroups',
            field=models.ManyToManyField(related_name='publications', to='setup.TargetGroup'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='logo',
            field=models.ImageField(upload_to='publications/'),
        ),
    ]
