# Generated by Django 2.0.3 on 2018-03-27 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20180327_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.Image'),
        ),
    ]
