# Generated by Django 2.0.3 on 2018-03-27 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20180327_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='recurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.Recurrence'),
        ),
    ]
