# Generated by Django 2.0.3 on 2018-03-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_auto_20180327_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('contactName', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=1024)),
                ('phone', models.CharField(max_length=1024)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.Image')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='setup.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateName', models.CharField(max_length=1024)),
                ('dimensions', models.CharField(max_length=1024)),
                ('bleed', models.CharField(max_length=1024)),
                ('price', models.CharField(max_length=1024)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='setup.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='deadline',
        ),
        migrations.DeleteModel(
            name='Deadline',
        ),
        migrations.AddField(
            model_name='rate',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.Publication'),
        ),
    ]
