# Generated by Django 2.0.3 on 2018-03-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_auto_20180327_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Image'),
        ),
        migrations.AlterField(
            model_name='client',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Client'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Image'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Client'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Publication'),
        ),
    ]
