# Generated by Django 2.0.3 on 2018-04-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_auto_20180410_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='targetGroups',
            field=models.ManyToManyField(blank=True, related_name='publications', to='setup.TargetGroup'),
        ),
    ]
