# Generated by Django 2.0.3 on 2018-04-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_auto_20180411_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='recurrence',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('full campaign', 'Full Campaign')], default='weekly', max_length=15),
        ),
    ]
